/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stato del servizio */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Il servizio è attivo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utente corrente, impostazioni AI e quota della piattaforma */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utente corrente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancella l'utente, i suoi file e tutti i suoi dati */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteAccountInput"];
                };
            };
            responses: {
                /** @description Account cancellato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea lo scontrino e restituisce un URL firmato di upload (2 minuti) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadUrlInput"];
                };
            };
            responses: {
                /** @description URL di upload creato */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadUrl"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Scontrino già caricato (stesso sha256) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DuplicateError"];
                    };
                };
                /** @description File troppo grande */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conferma l'upload: ricontrolla il file e accoda l'estrazione */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Upload accettato, estrazione in coda */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadAccepted"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stato non compatibile */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Il file caricato non corrisponde a quanto dichiarato */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inserimento manuale (nessuna chiamata LLM) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualReceiptInput"];
                };
            };
            responses: {
                /** @description Scontrino creato */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReceiptDetail"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elenco paginato degli scontrini */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    from?: string;
                    to?: string;
                    status?: components["schemas"]["ReceiptStatus"];
                    category?: components["schemas"]["Category"];
                    source?: components["schemas"]["ReceiptSource"];
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di scontrini */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReceiptList"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dettaglio con estrazione corrente e URL firmato del file (10 minuti) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dettaglio */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReceiptDetail"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Cancella file, estrazioni e righe */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellato */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/receipts/{id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storico delle estrazioni, dalla più recente */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Storico */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtractionHistory"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extractions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corregge l'estrazione corrente (items sostituisce tutte le righe) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExtractionPatch"];
                };
            };
            responses: {
                /** @description Estrazione aggiornata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtractionDetail"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stato non compatibile */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/receipts/{id}/reextract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rielabora lo scontrino creando una nuova estrazione (non per source=manual) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReextractInput"];
                };
            };
            responses: {
                /** @description Rielaborazione in coda */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadAccepted"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stato non compatibile */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impostazioni AI, chiavi salvate (solo last4) e quota della piattaforma */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Impostazioni AI */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiSettings"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Modalità (platform/byok), provider, modello e fallback sulla piattaforma */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiSettingsInput"];
                };
            };
            responses: {
                /** @description Impostazioni aggiornate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiSettings"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nessuna chiave salvata per il provider (USER_KEY_MISSING) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai/keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Verifica la chiave sul provider, poi la cifra e la salva */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: components["schemas"]["Provider"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApiKeyInput"];
                };
            };
            responses: {
                /** @description Chiave salvata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyInfo"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Chiave rifiutata (USER_KEY_INVALID) o senza quota */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Provider non raggiungibile (PROVIDER_UNAVAILABLE) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Cancella la chiave; se era in uso torna a mode=platform */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: components["schemas"]["Provider"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chiave cancellata */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Risorsa non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prova chiave e modello con una chiamata minima */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiTestInput"];
                };
            };
            responses: {
                /** @description Esito della prova */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiTestResult"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nessuna chiave salvata per il provider (USER_KEY_MISSING) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Chiave salvata non decifrabile (USER_KEY_INVALID) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modelli del provider, caricati in tempo reale */
        get: {
            parameters: {
                query: {
                    provider: components["schemas"]["Provider"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Modelli disponibili */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Nessuna chiave salvata per il provider (USER_KEY_MISSING) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Chiave rifiutata (USER_KEY_INVALID) o senza quota */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Provider non raggiungibile (PROVIDER_UNAVAILABLE) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consumo LLM: totali, serie per giorno o per modello, dettaglio per modello */
        get: {
            parameters: {
                query?: {
                    /** @description Default: primo giorno del mese corrente */
                    from?: string;
                    /** @description Incluso; con la sola data comprende l'intera giornata. Default: adesso */
                    to?: string;
                    groupBy?: "day" | "model";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consumo nel periodo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageSummary"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ultime chiamate LLM con il nome dell'esercente collegato */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagina di chiamate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageCallList"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiche di spesa: totali, per categoria, per periodo, esercenti e sorgente */
        get: {
            parameters: {
                query?: {
                    /** @description Data dello scontrino (acquisto o, se manca, caricamento) da cui partire. Default: nessun limite */
                    from?: string;
                    /** @description Incluso; con la sola data comprende l'intera giornata. Default: nessun limite */
                    to?: string;
                    granularity?: "month" | "year";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistiche nel periodo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stats"];
                    };
                };
                /** @description Richiesta non valida */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token mancante o non valido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Troppe richieste */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Errore interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Servizio temporaneamente non disponibile */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {boolean} */
            ok: true;
            /** @example 0.1.0 */
            version: string;
        };
        Me: {
            /** Format: uuid */
            userId: string;
            email: string | null;
            ai: {
                /** @enum {string} */
                mode: "platform" | "byok";
                provider: string | null;
                model: string | null;
            };
            platformQuota: {
                used: number;
                limit: number;
            };
        };
        Error: {
            error: {
                /** @example NOT_FOUND */
                code: string;
                message: string;
                requestId: string;
            };
        };
        DeleteAccountInput: {
            /**
             * @description Conferma esplicita della cancellazione
             * @enum {string}
             */
            confirm: "ELIMINA";
        };
        UploadUrl: {
            /** Format: uuid */
            receiptId: string;
            path: string;
            /** Format: uri */
            uploadUrl: string;
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        DuplicateError: {
            error: {
                /** @enum {string} */
                code: "DUPLICATE";
                message: string;
                requestId: string;
                /** Format: uuid */
                duplicateOf: string;
            };
        };
        UploadUrlInput: {
            /** @enum {string} */
            source: "camera" | "file";
            sha256: string;
            mimeType: components["schemas"]["MimeType"];
            sizeBytes: number;
            /** @example 2026-10-04T12:30:00+02:00 */
            capturedAt?: string;
            originalFilename?: string;
        };
        /** @enum {string} */
        MimeType: "image/jpeg" | "image/png" | "image/webp" | "application/pdf";
        UploadAccepted: {
            /** @enum {string} */
            status: "uploaded";
        };
        ReceiptDetail: {
            receipt: components["schemas"]["Receipt"];
            /** Format: uri */
            fileUrl?: string;
            extraction?: components["schemas"]["ExtractionDetail"];
            items: components["schemas"]["ReceiptItem"][];
            usage?: {
                provider: string;
                model: string;
                totalTokens: number | null;
                costUsd: number | null;
            };
        };
        Receipt: {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["ReceiptSource"];
            status: components["schemas"]["ReceiptStatus"];
            originalFilename: string | null;
            sha256: string | null;
            mimeType: string | null;
            sizeBytes: number | null;
            /** Format: date-time */
            capturedAt: string | null;
            /**
             * @description Motivo del fallimento quando status=failed. Valori attuali: NOT_A_RECEIPT, INVALID_OUTPUT, UNSUPPORTED_FILE_TYPE, USER_KEY_MISSING, USER_KEY_INVALID, USER_KEY_QUOTA, PLATFORM_QUOTA_EXCEEDED, AI_NOT_CONFIGURED, LLM_UNAVAILABLE, FILE_UNAVAILABLE, INTERNAL.
             * @example NOT_A_RECEIPT
             */
            errorCode: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        ReceiptSource: "camera" | "file" | "manual";
        /** @enum {string} */
        ReceiptStatus: "pending_upload" | "uploaded" | "processing" | "extracted" | "failed";
        ExtractionDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            receiptId: string;
            /** @enum {string} */
            method: "llm" | "manual";
            provider: string | null;
            model: string | null;
            /** @enum {string|null} */
            keySource: "platform" | "user" | null;
            promptVersion: string | null;
            merchantName: string | null;
            merchantVat: string | null;
            merchantAddress: string | null;
            /** Format: date-time */
            purchasedAt: string | null;
            currency: string;
            total: number | null;
            taxTotal: number | null;
            paymentMethod: components["schemas"]["PaymentMethod"] | null;
            category: components["schemas"]["Category"] | null;
            confidence: number | null;
            notes: string | null;
            isCurrent: boolean;
            editedByUser: boolean;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["ReceiptItem"][];
        };
        /** @enum {string} */
        PaymentMethod: "contanti" | "carta" | "bancomat" | "altro" | "sconosciuto";
        /** @enum {string} */
        Category: "alimentari" | "ristorazione" | "trasporti" | "carburante" | "salute" | "casa" | "abbigliamento" | "tecnologia" | "svago" | "servizi" | "altro";
        ReceiptItem: {
            /** Format: uuid */
            id: string;
            position: number;
            description: string;
            quantity: number | null;
            unitPrice: number | null;
            amount: number | null;
            vatRate: number | null;
            category: components["schemas"]["Category"] | null;
        };
        ManualReceiptInput: {
            merchantName: string;
            merchantVat?: string;
            /** @example 2026-10-04T12:30:00+02:00 */
            purchasedAt: string;
            /** @example EUR */
            currency?: string;
            total: number;
            taxTotal?: number;
            paymentMethod: components["schemas"]["PaymentMethod"];
            category: components["schemas"]["Category"];
            notes?: string;
            items?: {
                description: string;
                quantity?: number;
                unitPrice?: number;
                amount?: number;
                vatRate?: number;
                category?: components["schemas"]["Category"];
            }[];
        };
        ReceiptList: {
            items: components["schemas"]["ReceiptListItem"][];
            nextCursor: string | null;
        };
        ReceiptListItem: {
            /** Format: uuid */
            id: string;
            source: components["schemas"]["ReceiptSource"];
            status: components["schemas"]["ReceiptStatus"];
            merchantName: string | null;
            /** Format: date-time */
            purchasedAt: string | null;
            total: number | null;
            currency: string | null;
            category: components["schemas"]["Category"] | null;
            /** Format: uri */
            thumbnailUrl?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ExtractionHistory: {
            items: components["schemas"]["ExtractionDetail"][];
        };
        ExtractionPatch: {
            merchantName?: string | null;
            merchantVat?: string | null;
            merchantAddress?: string | null;
            /** @example 2026-10-04T12:30:00+02:00 */
            purchasedAt?: string | null;
            /** @example EUR */
            currency?: string;
            total?: number | null;
            taxTotal?: number | null;
            paymentMethod?: components["schemas"]["PaymentMethod"] | null;
            category?: components["schemas"]["Category"] | null;
            notes?: string | null;
            items?: {
                description: string;
                quantity?: number;
                unitPrice?: number;
                amount?: number;
                vatRate?: number;
                category?: components["schemas"]["Category"];
            }[];
        };
        ReextractInput: {
            /** @enum {string} */
            provider?: "anthropic" | "openai" | "openrouter";
            model?: string;
        };
        AiSettings: {
            mode: components["schemas"]["AiMode"];
            provider: components["schemas"]["Provider"] | null;
            model: string | null;
            fallbackToPlatform: boolean;
            keys: components["schemas"]["ApiKeyInfo"][];
            platformQuota: components["schemas"]["PlatformQuota"];
        };
        /** @enum {string} */
        AiMode: "platform" | "byok";
        /** @enum {string} */
        Provider: "anthropic" | "openai" | "openrouter";
        ApiKeyInfo: {
            provider: components["schemas"]["Provider"];
            /** @description Ultimi 4 caratteri della chiave */
            last4: string;
            /** Format: date-time */
            verifiedAt: string | null;
        };
        PlatformQuota: {
            used: number;
            limit: number;
        };
        /** @description I campi omessi restano invariati. Con mode=byok servono provider, model e una chiave salvata per il provider. */
        AiSettingsInput: {
            mode: components["schemas"]["AiMode"];
            provider?: components["schemas"]["Provider"] | null;
            model?: string | null;
            fallbackToPlatform?: boolean;
        };
        ApiKeyInput: {
            /** @description Chiave API del provider: non viene mai restituita */
            apiKey: string;
        };
        AiTestResult: {
            ok: boolean;
            error?: {
                /** @enum {string} */
                code: "USER_KEY_INVALID" | "USER_KEY_QUOTA" | "LLM_UNAVAILABLE";
                message: string;
            };
        };
        /** @description Senza apiKey si usa la chiave salvata dell'utente per il provider. */
        AiTestInput: {
            provider: components["schemas"]["Provider"];
            /** @description ID del modello restituito da GET /v1/settings/ai/models */
            model: string;
            /** @description Chiave API del provider: non viene mai restituita */
            apiKey?: string;
        };
        ModelList: {
            models: components["schemas"]["ModelInfo"][];
        };
        ModelInfo: {
            id: string;
            label: string;
            /** @description null se il provider non dichiara la capacità */
            supportsImages: boolean | null;
            /** @description null se il provider non dichiara la capacità */
            supportsPdf: boolean | null;
        };
        UsageSummary: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            totals: components["schemas"]["UsageTotals"];
            /** @description Serie raggruppata secondo groupBy */
            series: {
                /** @description Giorno (YYYY-MM-DD, Europe/Rome) oppure provider/model secondo groupBy */
                key: string;
                calls: number;
                inputTokens: number;
                outputTokens: number;
                /** @description Somma dei costi noti in USD */
                costUsd: number;
                /** @description Chiamate senza prezzo in model_prices (costo non incluso) */
                unpricedCalls: number;
            }[];
            byModel: {
                provider: string;
                model: string;
                calls: number;
                inputTokens: number;
                outputTokens: number;
                /** @description Somma dei costi noti in USD */
                costUsd: number;
                /** @description Chiamate senza prezzo in model_prices (costo non incluso) */
                unpricedCalls: number;
            }[];
        };
        UsageTotals: {
            calls: number;
            inputTokens: number;
            outputTokens: number;
            /** @description Somma dei costi noti in USD */
            costUsd: number;
            /** @description Chiamate senza prezzo in model_prices (costo non incluso) */
            unpricedCalls: number;
        };
        UsageCallList: {
            items: components["schemas"]["UsageCall"][];
            nextCursor: string | null;
        };
        UsageCall: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            operation: "extract" | "reextract" | "key_test";
            provider: string;
            model: string;
            /** @enum {string} */
            keySource: "platform" | "user";
            inputTokens: number | null;
            outputTokens: number | null;
            totalTokens: number | null;
            costUsd: number | null;
            latencyMs: number;
            success: boolean;
            errorCode: string | null;
            /** Format: uuid */
            receiptId: string | null;
            merchantName: string | null;
        };
        /** @description Statistiche sulle estrazioni correnti degli scontrini estratti */
        Stats: {
            /** Format: date-time */
            from: string | null;
            /**
             * Format: date-time
             * @description Limite superiore esclusivo, già normalizzato (inizio del giorno dopo se in query c'era la sola data)
             */
            to: string | null;
            /** @enum {string} */
            granularity: "month" | "year";
            totals: components["schemas"]["StatsTotals"];
            byCategory: {
                category: components["schemas"]["Category"];
                /** @description Somma dei totali, 2 decimali, senza conversione di valuta */
                total: number;
                nReceipts: number;
            }[];
            byPeriod: {
                /**
                 * @description YYYY-MM o YYYY (Europe/Rome)
                 * @example 2026-10
                 */
                period: string;
                /** @description Somma dei totali, 2 decimali, senza conversione di valuta */
                total: number;
                nReceipts: number;
            }[];
            topMerchants: {
                merchantName: string;
                /** @description Somma dei totali, 2 decimali, senza conversione di valuta */
                total: number;
                nReceipts: number;
            }[];
            bySource: {
                source: components["schemas"]["ReceiptSource"];
                /** @description Somma dei totali, 2 decimali, senza conversione di valuta */
                total: number;
                nReceipts: number;
            }[];
        };
        StatsTotals: {
            /** @description Somma dei totali, 2 decimali, senza conversione di valuta */
            total: number;
            nReceipts: number;
            /** @description Totale medio per scontrino, 2 decimali */
            average: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
